version: 2
jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:9-jessie-browsers
    steps:
      - checkout
      - run: npm install
      - run:
          name: Tests
          command: 'npm run test-ci'

workflows:
  version: 2
  build_and_test:
    jobs:
      - test:
          filters:
            branches:
              only: master
