version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:9-jessie-browsers
    steps:
      - checkout
      - run: npm install
  test:
    docker:
      - image: circleci/node:9-jessie-browsers
    steps:
      - checkout
      - run: npm install
      - run:
          name: Tests
          command: 'npm run test-ci'

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
